# Configuration pour MongoDB local
spring.data.mongodb.uri=mongodb://admin:password123@localhost:27017/buskrz?authSource=admin
spring.data.mongodb.database=buskrz

# Server Configuration
server.port=8080

# Logging pour déboguer
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.praksix.buskrz.config=DEBUG
logging.level.com.praksix.buskrz.security=DEBUG

