spring.application.name=buskrz

spring.threads.virtual.enabled=true

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}

# Server Configuration
server.port=${PORT:8080}

# CORS is configured in SecurityConfig.java

# Logging pour déboguer Spring Security
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.praksix.buskrz.config=DEBUG
logging.level.com.praksix.buskrz.security=DEBUG

management.security.enabled=false
