spring.application.name=buskrz

spring.threads.virtual.enabled=true

# MongoDB Configuration
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DATABASE}

# Server Configuration
server.port=${PORT:8080}

# CORS is configured in SecurityConfig.java

# Logging pour déboguer Spring Security
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.com.praksix.buskrz.config=DEBUG
logging.level.com.praksix.buskrz.security=DEBUG

management.security.enabled=false

# 🖼️ Configuration pour l'upload de fichiers (GridFS)
# max-file-size : Taille maximale d'un seul fichier (10 Mo)
# max-request-size : Taille maximale de la requête totale (10 Mo)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
